-- Migration initiale pour prod : ajout colonne galerie et table refresh_tokens
ALTER TABLE offers ADD COLUMN IF NOT EXISTS gallery_urls TEXT;

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(200) NOT NULL UNIQUE,
    username VARCHAR(150) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
