server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mobility_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: mobility_user
    password: mobility_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  devtools:
    restart:
      enabled: true

logging:
  level:
    com.mobility: DEBUG
    org.hibernate.SQL: DEBUG

app:
  jwt:
    secret: "mobilityJWTSuperSecretKeyForDevelopment2024!"
    expiration: 86400000
