-- Schéma de base appliqué avant data.sql (H2/postgres compatibles)
-- Ajout de la colonne galerie pour les offres (stockée en JSON string)
ALTER TABLE offers ADD COLUMN IF NOT EXISTS gallery_urls TEXT;

-- Table de refresh tokens
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(200) NOT NULL UNIQUE,
    username VARCHAR(150) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
