name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build and test with Maven
      run: |
        cd backend
        mvn clean verify
    
#    - name: Code Quality Checks
#      run: |
#       cd backend
#       mvn checkstyle:check
#       mvn spotbugs:check
    
   - name: Deploy to staging
     if: github.ref == 'refs/heads/main'
     run: |
       echo "🚀 Déploiement automatique vers l'environnement de staging!"
       echo "Application déployée avec succès ✅"
